apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: default
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: imarcho/myapp:3732d8a90747f7a2a7e9fbf7c66dd3e7bc4bf4c3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: SQLITE_DB_LOCATION
              value: "/data/todos.db"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
