apiVersion: v1
kind: Service
metadata:
  name: to-do-app
  namespace: default
spec:
  selectors:
    app: to-do-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort