---
"on":
  push:
    branches: push-model
jobs:
  Setup_and_test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3

      - name: Node cache
        uses: actions/cache@v3
        with:
          path: ./app/node_modules
          key: yarn-${{ hashFiles('app/yarn.lock') }}-${{ runner.os }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: YARN install
        working-directory: ./app
        run: yarn install

      - name: Test
        working-directory: ./app
        env:
          SQLITE_DB_LOCATION: /tmp/todos/test.db
        run: mkdir -p /tmp/todos && yarn test

  Code_analysis:
    needs: Setup_and_test
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3

      - name: Init CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: "javascript"

      - name: Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "javascript"

  Build_and_scan:
    needs: Setup_and_test
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker build -t imarcho/myapp:V1 ./

      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.36.0
        with:
          image-ref: 'imarcho/myapp:V1'
          format: 'sarif'
          exit-code: 0
          output: 'trivy-results.sarif'

      - name: Results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'

  Deploy:
    needs: Build_and_scan
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:

      - name: Set k8s
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBECONFIG}}

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/to-do-app \
          to-do-app=imarcho/myapp:V1 -n default
          kubectl rollout status deployment/to-do-app -n default
